export enum Permission {
    READ = 'READ',
    WRITE = 'WRITE',
    DELETE = 'DELETE',
    ADMIN = 'ADMIN',
    USER_MANAGE = 'USER_MANAGE',
    ROLE_MANAGE = 'ROLE_MANAGE',
    SYSTEM_MANAGE = 'SYSTEM_MANAGE',
    AUDIT_VIEW = 'AUDIT_VIEW',
}
